{{- if eq .Values.environment "uat" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: angular-mf-ssl-cert
  namespace: {{.Values.environment}}-namespace
  annotations: 
    cert-manager.io/ingress-class: ingress-nginx-class-{{.Values.environment}}
spec:
  secretName: angular-mf-ssl-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - {{.Values.environment}}-{{.Values.hostName}}
{{- end }}
