apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{.Chart.Name}}-deployment-{{.Values.environment}}
 labels:
  app: {{.Chart.Name}}-deployment-{{.Values.environment}}

spec:
  selector:
    matchLabels:
      app: {{.Chart.Name}}-deployment-{{.Values.environment}}

  template:
    metadata:
      labels:
        app: {{.Chart.Name}}-deployment-{{.Values.environment}}
      annotations: # This checksum will change whenever the ConfigMap changes 
        checksum/common-config: {{ include (print $.Template.BasePath "/common-config.yaml") . | sha256sum }} 
        checksum/env-config: {{ include (print $.Template.BasePath (printf "/%s-config.yaml" .Values.environment)) . | sha256sum }}
    spec:
     containers:
       - name : {{.Chart.Name}}-{{.Values.pod.containerName}}-{{.Values.environment}}
         image: {{.Values.pod.imageName}}
         ports:
          - containerPort : {{.Values.pod.containerPort}} #this should match the port nginx listening on
         volumeMounts:
         - name: {{.Values.config.volume}}
           mountPath: /{{.Values.config.mountPath}}
           readOnly: true
         env:
           - name: env
             valueFrom:
               configMapKeyRef:
                  name: {{.Values.environment}}-{{.Values.config.name}}
                  key: env
           - name: protocol
             valueFrom:
               configMapKeyRef:
                  name: {{.Values.environment}}-{{.Values.config.name}}
                  key: protocol
           - name: nginxPort
             valueFrom:
               configMapKeyRef:
                  name: common-{{.Values.config.name}}
                  key: nginxPort
           - name: ingressPort
             valueFrom:
               configMapKeyRef:
                  name: common-{{.Values.config.name}}
                  key: ingressPort
           - name: remoteAName
             valueFrom:
               configMapKeyRef:
                  name: common-{{.Values.config.name}}
                  key: remoteAName
           - name: remoteBName
             valueFrom:
               configMapKeyRef:
                  name: common-{{.Values.config.name}}
                  key: remoteBName
           - name: hostName
             valueFrom:
               configMapKeyRef:
                  name: common-{{.Values.config.name}}
                  key: hostName
     volumes:
     - name: {{.Values.config.volume}}
       configMap:
         name: {{.Values.environment}}-{{.Values.config.name}}
     - name: common-{{.Values.config.volume}}
       configMap:
         name: common-{{.Values.config.name}}


#we are loading all environment variables from the config map with name :dev-app-config


#helm install helm-release helm-test
#helm upgrade helm-release helm-test