apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microfrontends-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "256m"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
spec:
  rules:
    - host: {{.Values.hostName}}
      http:
        paths:
          - path: /{{.Values.environment}}/{{.Values.remoteA.path}}/
            pathType: Prefix
            backend:
              service:
                name: {{.Values.remoteA.name}}-service-{{.Values.environment}}
                port:
                  number: {{.Values.services.port}}
          - path: /{{.Values.environment}}/{{.Values.remoteB.path}}/
            pathType: Prefix
            backend:
              service:
                name: {{.Values.remoteB.name}}-service-{{.Values.environment}}
                port:
                  number: {{.Values.services.port}}
          - path: /{{.Values.environment}}/
            pathType: Prefix
            backend:
              service:
                name: {{.Values.services.name}}-{{.Values.environment}}
                port:
                  number: {{.Values.services.port}}
