apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microfrontends-ingress-{{.Values.environment}}
  annotations:
    kubernetes.io/ingress.class: ingress-nginx-class-{{.Values.environment}}
    nginx.ingress.kubernetes.io/proxy-body-size: "256m"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  {{- if eq .Values.environment "uat" }} 
  tls: 
  - hosts: 
      - {{.Values.environment}}-{{ .Values.hostName }} 
    secretName: {{ .Values.tlsSecretName }} 
  {{- end }}
  ingressClassName: ingress-nginx-class-{{.Values.environment}}
  rules:
    - host: {{.Values.environment}}-{{.Values.hostName}}
      http:
        paths:
          - path: /{{.Values.remoteA.path}}/
            pathType: Prefix
            backend:
              service:
                name: {{.Values.remoteA.name}}-service-{{.Values.environment}}
                port:
                  number: {{.Values.services.port}}
          - path: /{{.Values.remoteB.path}}/
            pathType: Prefix
            backend:
              service:
                name: {{.Values.remoteB.name}}-service-{{.Values.environment}}
                port:
                  number: {{.Values.services.port}}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.Values.services.name}}-{{.Values.environment}}
                port:
                  number: {{.Values.services.port}}
